<section id="vacancy-1">  
                 
                <h3>Job Vacancy-1</h3>
                <p><span>Job Role ID     : </span><span id="job1-Id">SE365</span></p>
                <p>Job Role Title  : Software Engineer</p>
                <p>Job Description : We are on the hunt for a talented and result driven Software Engineer to join our budding team. 
                                         The ideal applicant will be enthusiastic about producing high-quality software solutions, possess a 
                                         sound technical background, and be able to work well both independently and cooperatively in a 
                                         fast-paced workplace with the right mix of technical professionalism and soft skills.</p>       
                <p>Salary Range : 120,000 - 140,000 AUD per Annum</p>   
                <p>Reports to  : Software Systems Architect</p>                      
                <p>Key responsibilities :</p>
                    <ul> 
                        <li>Engage with cross-functional teams to develop, create, and implement new features.</li>
                        <li>To achieve the objectives of the project, write code that is clean, efficient, and easy to maintain.</li>
                        <li>Collaborate in code reviews to guarantee code quality and compatibility to coding standards.</li>
                        <li>Investigate , diagnose and troubleshoot software difficulties, and give prompt resolutions.</li>
                        <li>Discover, assess, and deploy new technologies on a continuous basis for optimal development efficiency.</li>
                    </ul>
                
                <p>Key Skills requiremets:</p>
                    <ul>
                        <li>Essential</li>
                        <li>
                            <ol>
                                <li>Bachelor's degree in Engineering, Computer Science, or a similar discipline.</li>
                                <li>A minimum of 2 years of full-time work experience developing software.</li>
                                <li>Full proficiency in at least one programming language, such as C++, Java, or Python.</li>
                                <li>A strong grasp of algorithms, data structures, and concepts.</li>
                                <li>Proven experience with web development frameworks, such as Angular, Flask, React, or Django, is required.</li>
                                <li>Good problem-solving abilities, including the capacity to troubleshoot and debug problems.</li>
                                <li>Outstanding interpersonal and communication abilities, with the capacity to work well in cross-functional teams.</li>
                                <li>The capacity to perform well in a dynamic, fast-paced setting and handle several activities at once.</li>
                            </ol>
                        </li>    
                        
                        <li>Preferable</li>
                        <li>
                            <ol>
                                <li>Working knowledge of cloud platforms like Google Cloud, Azure, or Amazon.</li>
                                <li>Working in agile development teams and being acquainted with agile processes.</li>
                                <li>Familiarity with CI/CD procedures and instruments.</li>
                                <li>Database management expertise, including knowledge of relational and non-relational databases like PostgreSQL, MongoDB, and MySQL.</li>
                                <li>Version Control Systems: Knowledge of version control programmes like Git.</li>
                            </ol>
                        </li>
                    </ul>        
  
            </section>
