
            <section id="vacancy-2"> 
               
                <h3>Job Vacancy-2</h3>  
                <p><span>Job Role ID     : </span><span id="job2-Id">PR268</span></p>
                <p>Job Role Title  : Project Manager - IT</p>
                <p>Job Description : We are seeking a versatile IT Project Manager to join our team and manage the efficient handling
                                             of our IT projects. The ideal applicant will have extensive experience in project management, a thorough grasp of 
                                             IT systems and technologies, and exceptional leadership and communication abilities.</p>       
                <p>Salary Range : 150,000 - 180,000 AUD per Annum</p>   
                <p>Reports to  : General Manager - IT</p>                      
                <p>Key responsibilities :</p>
                    <ul> 
                        <li>Manage the whole lifecycle of IT projects, from start to finish, ensuring that they are finished on schedule, within scope, and on budget.</li>
                        <li>Establish the project scope, goals, and deliverables in consultation with stakeholders and the other team members.</li>
                        <li>Create precise project plans, timetables, and budgets, and track progress towards important milestones and targets.</li>
                        <li>Ensure that all applicable policies, standards, and requirements are followed throughout the project's lifespan.</li>
                        <li>Coordinate and lead project teams, which include internal employees, external contractors, and consultants, to ensure successful cooperation and resource distribution.</li>
                    </ul>
                
                <p>Key Skills requirements:</p>
                    <ul>
                        <li>Essential</li>
                        <li>
                            <ol>
                                <li>Skilled with project management approaches (e.g., Agile, Waterfall) with a minimum of 5 years of professional experience</li>
                                <li>Technical aptitude and a thorough awareness of IT systems, technologies, and procedures related to the project area, as well as the ability to comprehend technical ideas and needs.</li>
                                <li>The ability to manage and influence stakeholders at all levels, such as senior management, clients, and project sponsors.</li>
                                <li>Versatility and flexibility to changing project needs, objectives, and restrictions.</li>
                                <li>Strong verbal and written communication skills are required to successfully interact with stakeholders, team members, and clients.</li>
                                <li>Risk handling and  skilled in identifying, assessing, and mitigating project risks to reduce their impact on project execution and outcomes.</li>
                            </ol>
                        </li>    
                        
                        <li>Preferable</li>
                        <li>
                            <ol>
                                <li>PMP (Project Management Professional) or other equivalent project management qualifications are advantageous.</li>
                                <li>Industry knowledge refers to familiarity with the specific industry or sector in which the initiatives are being conducted.</li>
                                <li>Experience with Agile approaches such as Scrum and Kanban, as well as Agile frameworks and practices.</li>
                                <li>Knowledge of quality assurance procedures and techniques for ensuring project outputs satisfy quality standards and compliance needs.</li>
                                <li>Fundamental grasp of business analysis methodologies and tools for gathering, analysing, and documenting project requirements.</li>
                            </ol>
                        </li>
                    </ul>        

            </section>