<nav class="navbar">&nbsp;&nbsp;&nbsp;
<span class="navbuttons"><a href="./index.php">About us</a></span> &nbsp;&nbsp;&nbsp; 
<span class="navbuttons"><a href="./jobs.php">Jobs</a></span> &nbsp;&nbsp;&nbsp; 
<span class="navbuttons"><a href="./apply.php">Apply</a></span> &nbsp;&nbsp;&nbsp; 
<span class="navbuttons"><a href="./about.php">About Myself</a></span> &nbsp;&nbsp;&nbsp;
<span class="navbuttons"><a href="./enhancements.php">Enhancements</a></span> &nbsp;&nbsp;&nbsp;
<span class="navbuttons"><a href="./enhancements2.php">Enhancements2</a></span> &nbsp;&nbsp;&nbsp;
<span class="navbuttons"><a href="./phpenhancements.php">PHP enhancements</a></span> &nbsp;&nbsp;&nbsp;
<span class="navbuttons"><a href="./ManagerLogin.php">Manager Login</a></span> &nbsp;&nbsp;&nbsp;


</nav>
        </header>